spring:
  datasource:
    url: jdbc:mysql://cdb-aanqm573.gz.tencentcdb.com:10120/robbendev-shop?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aarob2020#
  application:
    name: shop-all

  main:
    allow-bean-definition-overriding: true
